# notebook output을 위한 파일입니다.
# json 형식으로 저장되어 있습니다. formatter를 비활성화 하고 저장해주세요.
testcase_and_result = [
    {"que_number": 0, "lv": "", "kinds": "", "testcase": "", "result": ""},
    {"que_number": 1, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 2, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 3, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 4, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 5, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 6, "lv": 0, "kinds": "요구사항 구현"},
    {"que_number": 7, "lv": 0, "kinds": "정렬"},
    {"que_number": 8, "lv": 0, "kinds": "정렬"},
    {"que_number": 9, "lv": 0, "kinds": "정렬"},
    {"que_number": 10, "lv": 0, "kinds": "정렬"},
    {"que_number": 11, "lv": 0, "kinds": "정렬"},
    {"que_number": 12, "lv": 0, "kinds": "정렬"},
    {"que_number": 13, "lv": 0, "kinds": "정렬"},
    {"que_number": 14, "lv": 0, "kinds": "정렬"},
    {"que_number": 15, "lv": 0, "kinds": "정렬"},
    {"que_number": 16, "lv": 0, "kinds": "정렬"},
    {"que_number": 17, "lv": 0, "kinds": "정렬"},
    {"que_number": 18, "lv": 0, "kinds": "분석"},
    {"que_number": 19, "lv": 0, "kinds": "타입 확인"},
    {"que_number": 20, "lv": 0, "kinds": "타입 확인"},
    {"que_number": 21, "lv": 0, "kinds": "탐색"},
    {"que_number": 22, "lv": 0, "kinds": "탐색"},
    {"que_number": 23, "lv": 0, "kinds": "탐색"},
    {"que_number": 24, "lv": 1, "kinds": "탐색, 동적 프로그래밍, 카데인 알고리즘"},
    {"que_number": 25, "lv": 1, "kinds": "탐색, 에라토스테네스의 체"},
    {"que_number": 26, "lv": 0, "kinds": "탐색, 슬라이딩 윈도우"},
    {"que_number": 27, "lv": 1, "kinds": "탐색, 슬라이딩 윈도우"},
    {"que_number": 28, "lv": 1, "kinds": "탐색, 투 포인터"},
    {"que_number": 29, "lv": 0, "kinds": "비트 조작"},
    {"que_number": 30, "lv": 0, "kinds": "비트 조작"},
    {"que_number": 31, "lv": 0, "kinds": "비트 조작"},
    {"que_number": 32, "lv": 0, "kinds": "비트 조작"},
    {"que_number": 33, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 34, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 35, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 36, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 37, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 38, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 39, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 39, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 40, "lv": 0, "kinds": "정규표현식"},
    {"que_number": 41, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 42, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 43, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 44, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 45, "lv": 0, "kinds": "데이터 구조"},
    {"que_number": 46, "lv": 1, "kinds": "데이터 구조"},
    {"que_number": 47, "lv": 1, "kinds": "데이터 구조"},
    {"que_number": 48, "lv": 1, "kinds": "데이터 구조"},
    {"que_number": 49, "lv": 2, "kinds": "데이터 구조, 너비 우선 탐색(BFS)"}
    {"que_number": 50, "lv": 2, "kinds": "데이터 구조, 깊이 우선 탐색(DFS)"}
]
